/**
 * Generated by scripts/build-control-glyphs.mjs. Do not edit directly.
 * Canonical source: assets/control-glyphs/manifest.json
 */

'use strict';

const family = {
  "provider": "Phosphor",
  "package": "@phosphor-icons/core",
  "version": "2.1.1",
  "weight": "regular",
  "license": "MIT",
  "source": "https://github.com/phosphor-icons/phosphor-core",
  "viewBox": "0 0 256 256",
  "defaultSize": 16,
  "sizes": [
    12,
    16,
    20
  ],
  "minimumHitTarget": 44
};
const controlGlyphs = {
  "control.add": {
    "semantic": "control.add",
    "label": "Add",
    "provider": "Phosphor",
    "providerIcon": "plus",
    "weight": "regular",
    "usage": "Create or add an item.",
    "slots": [
      "button.icon-only",
      "button.leading",
      "table.action"
    ],
    "animated": false,
    "viewBox": "0 0 256 256",
    "asset": "assets/control-glyphs/svg/control.add.svg",
    "body": "<g fill=\"currentColor\"><path d=\"M224,128a8,8,0,0,1-8,8H136v80a8,8,0,0,1-16,0V136H40a8,8,0,0,1,0-16h80V40a8,8,0,0,1,16,0v80h80A8,8,0,0,1,224,128Z\"/></g>"
  },
  "control.back": {
    "semantic": "control.back",
    "label": "Back",
    "provider": "Phosphor",
    "providerIcon": "arrow-left",
    "weight": "regular",
    "usage": "Return to the preceding view or hierarchy level.",
    "slots": [
      "button.leading",
      "navigation.leading"
    ],
    "animated": false,
    "viewBox": "0 0 256 256",
    "asset": "assets/control-glyphs/svg/control.back.svg",
    "body": "<g fill=\"currentColor\"><path d=\"M224,128a8,8,0,0,1-8,8H59.31l58.35,58.34a8,8,0,0,1-11.32,11.32l-72-72a8,8,0,0,1,0-11.32l72-72a8,8,0,0,1,11.32,11.32L59.31,120H216A8,8,0,0,1,224,128Z\"/></g>"
  },
  "control.close": {
    "semantic": "control.close",
    "label": "Close",
    "provider": "Phosphor",
    "providerIcon": "x",
    "weight": "regular",
    "usage": "Dismiss a dialog, sheet or transient surface.",
    "slots": [
      "button.icon-only",
      "dialog.close",
      "sheet.close"
    ],
    "animated": false,
    "viewBox": "0 0 256 256",
    "asset": "assets/control-glyphs/svg/control.close.svg",
    "body": "<g fill=\"currentColor\"><path d=\"M205.66,194.34a8,8,0,0,1-11.32,11.32L128,139.31,61.66,205.66a8,8,0,0,1-11.32-11.32L116.69,128,50.34,61.66A8,8,0,0,1,61.66,50.34L128,116.69l66.34-66.35a8,8,0,0,1,11.32,11.32L139.31,128Z\"/></g>"
  },
  "control.confirm": {
    "semantic": "control.confirm",
    "label": "Confirm",
    "provider": "Phosphor",
    "providerIcon": "check",
    "weight": "regular",
    "usage": "Confirm a selection or completed control state.",
    "slots": [
      "button.leading",
      "checkbox.indicator",
      "select.indicator",
      "status.leading"
    ],
    "animated": false,
    "viewBox": "0 0 256 256",
    "asset": "assets/control-glyphs/svg/control.confirm.svg",
    "body": "<g fill=\"currentColor\"><path d=\"M229.66,77.66l-128,128a8,8,0,0,1-11.32,0l-56-56a8,8,0,0,1,11.32-11.32L96,188.69,218.34,66.34a8,8,0,0,1,11.32,11.32Z\"/></g>"
  },
  "control.copy": {
    "semantic": "control.copy",
    "label": "Copy",
    "provider": "Phosphor",
    "providerIcon": "copy",
    "weight": "regular",
    "usage": "Copy content or a value.",
    "slots": [
      "button.icon-only",
      "button.leading",
      "table.action"
    ],
    "animated": false,
    "viewBox": "0 0 256 256",
    "asset": "assets/control-glyphs/svg/control.copy.svg",
    "body": "<g fill=\"currentColor\"><path d=\"M216,32H88a8,8,0,0,0-8,8V80H40a8,8,0,0,0-8,8V216a8,8,0,0,0,8,8H168a8,8,0,0,0,8-8V176h40a8,8,0,0,0,8-8V40A8,8,0,0,0,216,32ZM160,208H48V96H160Zm48-48H176V88a8,8,0,0,0-8-8H96V48H208Z\"/></g>"
  },
  "control.disclosure": {
    "semantic": "control.disclosure",
    "label": "Disclose",
    "provider": "Phosphor",
    "providerIcon": "caret-down",
    "weight": "regular",
    "usage": "Reveal a menu, list or additional content.",
    "slots": [
      "navigation.trailing",
      "select.disclosure"
    ],
    "animated": false,
    "viewBox": "0 0 256 256",
    "asset": "assets/control-glyphs/svg/control.disclosure.svg",
    "body": "<g fill=\"currentColor\"><path d=\"M213.66,101.66l-80,80a8,8,0,0,1-11.32,0l-80-80A8,8,0,0,1,53.66,90.34L128,164.69l74.34-74.35a8,8,0,0,1,11.32,11.32Z\"/></g>"
  },
  "control.edit": {
    "semantic": "control.edit",
    "label": "Edit",
    "provider": "Phosphor",
    "providerIcon": "pencil-simple",
    "weight": "regular",
    "usage": "Modify an existing item or value.",
    "slots": [
      "button.icon-only",
      "button.leading",
      "table.action"
    ],
    "animated": false,
    "viewBox": "0 0 256 256",
    "asset": "assets/control-glyphs/svg/control.edit.svg",
    "body": "<g fill=\"currentColor\"><path d=\"M227.31,73.37,182.63,28.68a16,16,0,0,0-22.63,0L36.69,152A15.86,15.86,0,0,0,32,163.31V208a16,16,0,0,0,16,16H92.69A15.86,15.86,0,0,0,104,219.31L227.31,96a16,16,0,0,0,0-22.63ZM92.69,208H48V163.31l88-88L180.69,120ZM192,108.68,147.31,64l24-24L216,84.68Z\"/></g>"
  },
  "control.external": {
    "semantic": "control.external",
    "label": "Open externally",
    "provider": "Phosphor",
    "providerIcon": "arrow-square-out",
    "weight": "regular",
    "usage": "Open a destination outside the current application context.",
    "slots": [
      "button.trailing",
      "link.trailing",
      "table.action"
    ],
    "animated": false,
    "viewBox": "0 0 256 256",
    "asset": "assets/control-glyphs/svg/control.external.svg",
    "body": "<g fill=\"currentColor\"><path d=\"M224,104a8,8,0,0,1-16,0V59.32l-66.33,66.34a8,8,0,0,1-11.32-11.32L196.68,48H152a8,8,0,0,1,0-16h64a8,8,0,0,1,8,8Zm-40,24a8,8,0,0,0-8,8v72H48V80h72a8,8,0,0,0,0-16H48A16,16,0,0,0,32,80V208a16,16,0,0,0,16,16H176a16,16,0,0,0,16-16V136A8,8,0,0,0,184,128Z\"/></g>"
  },
  "control.filter": {
    "semantic": "control.filter",
    "label": "Filter",
    "provider": "Phosphor",
    "providerIcon": "funnel",
    "weight": "regular",
    "usage": "Filter a collection or data view.",
    "slots": [
      "button.icon-only",
      "button.leading",
      "table.action"
    ],
    "animated": false,
    "viewBox": "0 0 256 256",
    "asset": "assets/control-glyphs/svg/control.filter.svg",
    "body": "<g fill=\"currentColor\"><path d=\"M230.6,49.53A15.81,15.81,0,0,0,216,40H40A16,16,0,0,0,28.19,66.76l.08.09L96,139.17V216a16,16,0,0,0,24.87,13.32l32-21.34A16,16,0,0,0,160,194.66V139.17l67.74-72.32.08-.09A15.8,15.8,0,0,0,230.6,49.53ZM40,56h0Zm106.18,74.58A8,8,0,0,0,144,136v58.66L112,216V136a8,8,0,0,0-2.16-5.47L40,56H216Z\"/></g>"
  },
  "control.loading": {
    "semantic": "control.loading",
    "label": "Loading",
    "provider": "Phosphor",
    "providerIcon": "spinner-gap",
    "weight": "regular",
    "usage": "Indicate progressive work without implying completion.",
    "slots": [
      "button.leading",
      "loading.indicator",
      "status.leading"
    ],
    "animated": true,
    "viewBox": "0 0 256 256",
    "asset": "assets/control-glyphs/svg/control.loading.svg",
    "body": "<g fill=\"currentColor\"><path d=\"M136,32V64a8,8,0,0,1-16,0V32a8,8,0,0,1,16,0Zm88,88H192a8,8,0,0,0,0,16h32a8,8,0,0,0,0-16Zm-45.09,47.6a8,8,0,0,0-11.31,11.31l22.62,22.63a8,8,0,0,0,11.32-11.32ZM128,184a8,8,0,0,0-8,8v32a8,8,0,0,0,16,0V192A8,8,0,0,0,128,184ZM77.09,167.6,54.46,190.22a8,8,0,0,0,11.32,11.32L88.4,178.91A8,8,0,0,0,77.09,167.6ZM72,128a8,8,0,0,0-8-8H32a8,8,0,0,0,0,16H64A8,8,0,0,0,72,128ZM65.78,54.46A8,8,0,0,0,54.46,65.78L77.09,88.4A8,8,0,0,0,88.4,77.09Z\"/></g>"
  },
  "control.more": {
    "semantic": "control.more",
    "label": "More actions",
    "provider": "Phosphor",
    "providerIcon": "dots-three",
    "weight": "regular",
    "usage": "Open an overflow menu of additional actions.",
    "slots": [
      "button.icon-only",
      "table.action"
    ],
    "animated": false,
    "viewBox": "0 0 256 256",
    "asset": "assets/control-glyphs/svg/control.more.svg",
    "body": "<g fill=\"currentColor\"><path d=\"M140,128a12,12,0,1,1-12-12A12,12,0,0,1,140,128Zm56-12a12,12,0,1,0,12,12A12,12,0,0,0,196,116ZM60,116a12,12,0,1,0,12,12A12,12,0,0,0,60,116Z\"/></g>"
  },
  "control.refresh": {
    "semantic": "control.refresh",
    "label": "Refresh",
    "provider": "Phosphor",
    "providerIcon": "arrow-clockwise",
    "weight": "regular",
    "usage": "Refresh or synchronize the current data.",
    "slots": [
      "button.icon-only",
      "button.leading",
      "table.action"
    ],
    "animated": false,
    "viewBox": "0 0 256 256",
    "asset": "assets/control-glyphs/svg/control.refresh.svg",
    "body": "<g fill=\"currentColor\"><path d=\"M240,56v48a8,8,0,0,1-8,8H184a8,8,0,0,1,0-16H211.4L184.81,71.64l-.25-.24a80,80,0,1,0-1.67,114.78,8,8,0,0,1,11,11.63A95.44,95.44,0,0,1,128,224h-1.32A96,96,0,1,1,195.75,60L224,85.8V56a8,8,0,1,1,16,0Z\"/></g>"
  },
  "control.remove": {
    "semantic": "control.remove",
    "label": "Remove",
    "provider": "Phosphor",
    "providerIcon": "minus",
    "weight": "regular",
    "usage": "Remove an item from a collection without implying permanent deletion.",
    "slots": [
      "button.icon-only",
      "button.leading",
      "table.action"
    ],
    "animated": false,
    "viewBox": "0 0 256 256",
    "asset": "assets/control-glyphs/svg/control.remove.svg",
    "body": "<g fill=\"currentColor\"><path d=\"M224,128a8,8,0,0,1-8,8H40a8,8,0,0,1,0-16H216A8,8,0,0,1,224,128Z\"/></g>"
  },
  "control.run": {
    "semantic": "control.run",
    "label": "Run",
    "provider": "Phosphor",
    "providerIcon": "play",
    "weight": "regular",
    "usage": "Start or submit a governed operation.",
    "slots": [
      "button.icon-only",
      "button.leading"
    ],
    "animated": false,
    "viewBox": "0 0 256 256",
    "asset": "assets/control-glyphs/svg/control.run.svg",
    "body": "<g fill=\"currentColor\"><path d=\"M232.4,114.49,88.32,26.35a16,16,0,0,0-16.2-.3A15.86,15.86,0,0,0,64,39.87V216.13A15.94,15.94,0,0,0,80,232a16.07,16.07,0,0,0,8.36-2.35L232.4,141.51a15.81,15.81,0,0,0,0-27ZM80,215.94V40l143.83,88Z\"/></g>"
  },
  "state.error": {
    "semantic": "state.error",
    "label": "Error",
    "provider": "Phosphor",
    "providerIcon": "x-circle",
    "weight": "regular",
    "usage": "An error, blocked state or failed validation.",
    "slots": [
      "alert.leading",
      "field.message",
      "status.leading"
    ],
    "animated": false,
    "viewBox": "0 0 256 256",
    "asset": "assets/control-glyphs/svg/state.error.svg",
    "body": "<g fill=\"currentColor\"><path d=\"M165.66,101.66,139.31,128l26.35,26.34a8,8,0,0,1-11.32,11.32L128,139.31l-26.34,26.35a8,8,0,0,1-11.32-11.32L116.69,128,90.34,101.66a8,8,0,0,1,11.32-11.32L128,116.69l26.34-26.35a8,8,0,0,1,11.32,11.32ZM232,128A104,104,0,1,1,128,24,104.11,104.11,0,0,1,232,128Zm-16,0a88,88,0,1,0-88,88A88.1,88.1,0,0,0,216,128Z\"/></g>"
  },
  "state.info": {
    "semantic": "state.info",
    "label": "Information",
    "provider": "Phosphor",
    "providerIcon": "info",
    "weight": "regular",
    "usage": "Neutral information that requires attention but not intervention.",
    "slots": [
      "alert.leading",
      "field.message",
      "status.leading"
    ],
    "animated": false,
    "viewBox": "0 0 256 256",
    "asset": "assets/control-glyphs/svg/state.info.svg",
    "body": "<g fill=\"currentColor\"><path d=\"M128,24A104,104,0,1,0,232,128,104.11,104.11,0,0,0,128,24Zm0,192a88,88,0,1,1,88-88A88.1,88.1,0,0,1,128,216Zm16-40a8,8,0,0,1-8,8,16,16,0,0,1-16-16V128a8,8,0,0,1,0-16,16,16,0,0,1,16,16v40A8,8,0,0,1,144,176ZM112,84a12,12,0,1,1,12,12A12,12,0,0,1,112,84Z\"/></g>"
  },
  "state.success": {
    "semantic": "state.success",
    "label": "Success",
    "provider": "Phosphor",
    "providerIcon": "check-circle",
    "weight": "regular",
    "usage": "A successful, current or completed state.",
    "slots": [
      "alert.leading",
      "field.message",
      "status.leading"
    ],
    "animated": false,
    "viewBox": "0 0 256 256",
    "asset": "assets/control-glyphs/svg/state.success.svg",
    "body": "<g fill=\"currentColor\"><path d=\"M173.66,98.34a8,8,0,0,1,0,11.32l-56,56a8,8,0,0,1-11.32,0l-24-24a8,8,0,0,1,11.32-11.32L112,148.69l50.34-50.35A8,8,0,0,1,173.66,98.34ZM232,128A104,104,0,1,1,128,24,104.11,104.11,0,0,1,232,128Zm-16,0a88,88,0,1,0-88,88A88.1,88.1,0,0,0,216,128Z\"/></g>"
  },
  "state.warning": {
    "semantic": "state.warning",
    "label": "Warning",
    "provider": "Phosphor",
    "providerIcon": "warning",
    "weight": "regular",
    "usage": "A caution, review or escalating risk state.",
    "slots": [
      "alert.leading",
      "field.message",
      "status.leading"
    ],
    "animated": false,
    "viewBox": "0 0 256 256",
    "asset": "assets/control-glyphs/svg/state.warning.svg",
    "body": "<g fill=\"currentColor\"><path d=\"M236.8,188.09,149.35,36.22h0a24.76,24.76,0,0,0-42.7,0L19.2,188.09a23.51,23.51,0,0,0,0,23.72A24.35,24.35,0,0,0,40.55,224h174.9a24.35,24.35,0,0,0,21.33-12.19A23.51,23.51,0,0,0,236.8,188.09ZM222.93,203.8a8.5,8.5,0,0,1-7.48,4.2H40.55a8.5,8.5,0,0,1-7.48-4.2,7.59,7.59,0,0,1,0-7.72L120.52,44.21a8.75,8.75,0,0,1,15,0l87.45,151.87A7.59,7.59,0,0,1,222.93,203.8ZM120,144V104a8,8,0,0,1,16,0v40a8,8,0,0,1-16,0Zm20,36a12,12,0,1,1-12-12A12,12,0,0,1,140,180Z\"/></g>"
  }
};
const controlGlyphNames = [
  "control.add",
  "control.back",
  "control.close",
  "control.confirm",
  "control.copy",
  "control.disclosure",
  "control.edit",
  "control.external",
  "control.filter",
  "control.loading",
  "control.more",
  "control.refresh",
  "control.remove",
  "control.run",
  "state.error",
  "state.info",
  "state.success",
  "state.warning"
];
const controlGlyphSlots = [
  "alert.leading",
  "button.icon-only",
  "button.leading",
  "button.trailing",
  "checkbox.indicator",
  "dialog.close",
  "field.message",
  "link.trailing",
  "loading.indicator",
  "navigation.leading",
  "navigation.trailing",
  "select.disclosure",
  "select.indicator",
  "sheet.close",
  "status.leading",
  "table.action"
];

Object.freeze(family.sizes);
Object.freeze(family);
for (const definition of Object.values(controlGlyphs)) {
  Object.freeze(definition.slots);
  Object.freeze(definition);
}
Object.freeze(controlGlyphs);
Object.freeze(controlGlyphNames);
Object.freeze(controlGlyphSlots);

function hasControlGlyph(name) {
  return typeof name === 'string' && Object.prototype.hasOwnProperty.call(controlGlyphs, name);
}

function getControlGlyph(name) {
  if (!hasControlGlyph(name)) {
    throw new RangeError(`Unknown Frontira control glyph: ${String(name)}`);
  }
  return controlGlyphs[name];
}

function getControlGlyphAsset(name) {
  return getControlGlyph(name).asset;
}

function escapeAttribute(value) {
  return String(value)
    .replaceAll('&', '&amp;')
    .replaceAll('"', '&quot;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;');
}

function renderControlGlyph(name, options = {}) {
  if (!options || typeof options !== 'object' || Array.isArray(options)) {
    throw new TypeError('Control-glyph options must be an object');
  }
  const definition = getControlGlyph(name);
  const size = options.size === undefined ? family.defaultSize : options.size;
  if (!family.sizes.includes(size)) {
    throw new RangeError('Control-glyph size must be 12, 16, or 20');
  }
  if (options.className !== undefined && typeof options.className !== 'string') {
    throw new TypeError('Control-glyph className must be a string');
  }
  if (options.label !== undefined && typeof options.label !== 'string') {
    throw new TypeError('Control-glyph label must be a string');
  }
  const className = ['fr-control-glyph', options.className?.trim()].filter(Boolean).join(' ');
  const label = options.label?.trim();
  const accessibility = label
    ? `role="img" aria-label="${escapeAttribute(label)}"`
    : 'aria-hidden="true" focusable="false"';
  return `<svg xmlns="http://www.w3.org/2000/svg" class="${escapeAttribute(className)}" width="${size}" height="${size}" style="--fr-control-glyph-size: ${size}px" viewBox="${definition.viewBox}" fill="none" data-control-glyph="${definition.semantic}" ${accessibility}>${definition.body}</svg>`;
}

module.exports = {
  family,
  controlGlyphs,
  controlGlyphNames,
  controlGlyphSlots,
  hasControlGlyph,
  getControlGlyph,
  getControlGlyphAsset,
  renderControlGlyph,
};
