/** Generated by scripts/build-control-glyphs.mjs. Do not edit directly. */

export type ControlGlyphName =
  | 'control.add'
  | 'control.back'
  | 'control.close'
  | 'control.confirm'
  | 'control.copy'
  | 'control.disclosure'
  | 'control.edit'
  | 'control.external'
  | 'control.filter'
  | 'control.loading'
  | 'control.more'
  | 'control.refresh'
  | 'control.remove'
  | 'control.run'
  | 'state.error'
  | 'state.info'
  | 'state.success'
  | 'state.warning';

export type ControlGlyphSlot =
  | 'alert.leading'
  | 'button.icon-only'
  | 'button.leading'
  | 'button.trailing'
  | 'checkbox.indicator'
  | 'dialog.close'
  | 'field.message'
  | 'link.trailing'
  | 'loading.indicator'
  | 'navigation.leading'
  | 'navigation.trailing'
  | 'select.disclosure'
  | 'select.indicator'
  | 'sheet.close'
  | 'status.leading'
  | 'table.action';

export type ControlGlyphSize = 12 | 16 | 20;

export interface ControlGlyphFamily {
  readonly provider: 'Phosphor';
  readonly package: '@phosphor-icons/core';
  readonly version: '2.1.1';
  readonly weight: 'regular';
  readonly license: 'MIT';
  readonly source: string;
  readonly viewBox: '0 0 256 256';
  readonly defaultSize: 16;
  readonly sizes: readonly [12, 16, 20];
  readonly minimumHitTarget: number;
}

export interface ControlGlyphDefinition {
  readonly semantic: ControlGlyphName;
  readonly label: string;
  readonly provider: 'Phosphor';
  readonly providerIcon: string;
  readonly weight: 'regular';
  readonly usage: string;
  readonly slots: readonly ControlGlyphSlot[];
  readonly animated: boolean;
  readonly viewBox: '0 0 256 256';
  readonly asset: string;
  readonly body: string;
}

export interface RenderControlGlyphOptions {
  readonly label?: string;
  readonly className?: string;
  readonly size?: ControlGlyphSize;
}

export const family: Readonly<ControlGlyphFamily>;
export const controlGlyphs: Readonly<Record<ControlGlyphName, Readonly<ControlGlyphDefinition>>>;
export const controlGlyphNames: readonly ControlGlyphName[];
export const controlGlyphSlots: readonly ControlGlyphSlot[];
export function hasControlGlyph(name: unknown): name is ControlGlyphName;
export function getControlGlyph(name: ControlGlyphName): Readonly<ControlGlyphDefinition>;
export function getControlGlyphAsset(name: ControlGlyphName): string;
export function renderControlGlyph(name: ControlGlyphName, options?: RenderControlGlyphOptions): string;
