/**
 * Generated by scripts/build-pictograms.mjs. Do not edit directly.
 * Canonical source: assets/pictograms/manifest.json
 */

'use strict';

const family = {
  "provider": "Phosphor",
  "package": "@phosphor-icons/core",
  "version": "2.1.1",
  "weight": "regular",
  "license": "MIT",
  "source": "https://github.com/phosphor-icons/phosphor-core",
  "viewBox": "0 0 256 256",
  "defaultSize": 24,
  "minimumSize": 16
};
const pictograms = {
  "activity.handoff": {
    "semantic": "activity.handoff",
    "label": "Handoff",
    "namespace": "activity",
    "provider": "Phosphor",
    "providerIcon": "arrows-left-right",
    "weight": "regular",
    "reserved": false,
    "usage": "Generic transfer of work or context between actors or systems.",
    "viewBox": "0 0 256 256",
    "asset": "assets/pictograms/svg/activity.handoff.svg",
    "body": "<path fill=\"currentColor\" d=\"m213.66 181.66l-32 32a8 8 0 0 1-11.32-11.32L188.69 184H48a8 8 0 0 1 0-16h140.69l-18.35-18.34a8 8 0 0 1 11.32-11.32l32 32a8 8 0 0 1 0 11.32m-139.32-64a8 8 0 0 0 11.32-11.32L67.31 88H208a8 8 0 0 0 0-16H67.31l18.35-18.34a8 8 0 0 0-11.32-11.32l-32 32a8 8 0 0 0 0 11.32Z\"/>"
  },
  "activity.meeting": {
    "semantic": "activity.meeting",
    "label": "Meeting",
    "namespace": "activity",
    "provider": "Phosphor",
    "providerIcon": "users",
    "weight": "regular",
    "reserved": false,
    "usage": "Generic meeting or working session. Never a named Frontira engagement.",
    "viewBox": "0 0 256 256",
    "asset": "assets/pictograms/svg/activity.meeting.svg",
    "body": "<path fill=\"currentColor\" d=\"M117.25 157.92a60 60 0 1 0-66.5 0a95.83 95.83 0 0 0-47.22 37.71a8 8 0 1 0 13.4 8.74a80 80 0 0 1 134.14 0a8 8 0 0 0 13.4-8.74a95.83 95.83 0 0 0-47.22-37.71M40 108a44 44 0 1 1 44 44a44.05 44.05 0 0 1-44-44m210.14 98.7a8 8 0 0 1-11.07-2.33A79.83 79.83 0 0 0 172 168a8 8 0 0 1 0-16a44 44 0 1 0-16.34-84.87a8 8 0 1 1-5.94-14.85a60 60 0 0 1 55.53 105.64a95.83 95.83 0 0 1 47.22 37.71a8 8 0 0 1-2.33 11.07\"/>"
  },
  "activity.review": {
    "semantic": "activity.review",
    "label": "Review",
    "namespace": "activity",
    "provider": "Phosphor",
    "providerIcon": "clipboard-text",
    "weight": "regular",
    "reserved": false,
    "usage": "Generic review, quality gate or assessment activity.",
    "viewBox": "0 0 256 256",
    "asset": "assets/pictograms/svg/activity.review.svg",
    "body": "<path fill=\"currentColor\" d=\"M168 152a8 8 0 0 1-8 8H96a8 8 0 0 1 0-16h64a8 8 0 0 1 8 8m-8-40H96a8 8 0 0 0 0 16h64a8 8 0 0 0 0-16m56-64v168a16 16 0 0 1-16 16H56a16 16 0 0 1-16-16V48a16 16 0 0 1 16-16h36.26a47.92 47.92 0 0 1 71.48 0H200a16 16 0 0 1 16 16M96 64h64a32 32 0 0 0-64 0m104-16h-26.75A47.9 47.9 0 0 1 176 64v8a8 8 0 0 1-8 8H88a8 8 0 0 1-8-8v-8a47.9 47.9 0 0 1 2.75-16H56v168h144Z\"/>"
  },
  "activity.workshop": {
    "semantic": "activity.workshop",
    "label": "Workshop",
    "namespace": "activity",
    "provider": "Phosphor",
    "providerIcon": "presentation-chart",
    "weight": "regular",
    "reserved": false,
    "usage": "Generic facilitated workshop. Never substitutes for a named engagement.",
    "viewBox": "0 0 256 256",
    "asset": "assets/pictograms/svg/activity.workshop.svg",
    "body": "<path fill=\"currentColor\" d=\"M216 40h-80V24a8 8 0 0 0-16 0v16H40a16 16 0 0 0-16 16v120a16 16 0 0 0 16 16h39.36l-21.61 27a8 8 0 0 0 12.5 10l29.59-37h56.32l29.59 37a8 8 0 1 0 12.5-10l-21.61-27H216a16 16 0 0 0 16-16V56a16 16 0 0 0-16-16m0 136H40V56h176zm-112-56v24a8 8 0 0 1-16 0v-24a8 8 0 0 1 16 0m32-16v40a8 8 0 0 1-16 0v-40a8 8 0 0 1 16 0m32-16v56a8 8 0 0 1-16 0V88a8 8 0 0 1 16 0\"/>"
  },
  "data.database": {
    "semantic": "data.database",
    "label": "Database",
    "namespace": "data",
    "provider": "Phosphor",
    "providerIcon": "database",
    "weight": "regular",
    "reserved": false,
    "usage": "Structured operational data or a database system.",
    "viewBox": "0 0 256 256",
    "asset": "assets/pictograms/svg/data.database.svg",
    "body": "<path fill=\"currentColor\" d=\"M128 24c-53.83 0-96 24.6-96 56v96c0 31.4 42.17 56 96 56s96-24.6 96-56V80c0-31.4-42.17-56-96-56m80 104c0 9.62-7.88 19.43-21.61 26.92C170.93 163.35 150.19 168 128 168s-42.93-4.65-58.39-13.08C55.88 147.43 48 137.62 48 128v-16.64c17.06 15 46.23 24.64 80 24.64s62.94-9.68 80-24.64ZM69.61 53.08C85.07 44.65 105.81 40 128 40s42.93 4.65 58.39 13.08C200.12 60.57 208 70.38 208 80s-7.88 19.43-21.61 26.92C170.93 115.35 150.19 120 128 120s-42.93-4.65-58.39-13.08C55.88 99.43 48 89.62 48 80s7.88-19.43 21.61-26.92m116.78 149.84C170.93 211.35 150.19 216 128 216s-42.93-4.65-58.39-13.08C55.88 195.43 48 185.62 48 176v-16.64c17.06 15 46.23 24.64 80 24.64s62.94-9.68 80-24.64V176c0 9.62-7.88 19.43-21.61 26.92\"/>"
  },
  "data.storage": {
    "semantic": "data.storage",
    "label": "Storage",
    "namespace": "data",
    "provider": "Phosphor",
    "providerIcon": "hard-drives",
    "weight": "regular",
    "reserved": false,
    "usage": "File, object or durable system storage.",
    "viewBox": "0 0 256 256",
    "asset": "assets/pictograms/svg/data.storage.svg",
    "body": "<path fill=\"currentColor\" d=\"M208 136H48a16 16 0 0 0-16 16v48a16 16 0 0 0 16 16h160a16 16 0 0 0 16-16v-48a16 16 0 0 0-16-16m0 64H48v-48h160zm0-160H48a16 16 0 0 0-16 16v48a16 16 0 0 0 16 16h160a16 16 0 0 0 16-16V56a16 16 0 0 0-16-16m0 64H48V56h160zm-16-24a12 12 0 1 1-12-12a12 12 0 0 1 12 12m0 96a12 12 0 1 1-12-12a12 12 0 0 1 12 12\"/>"
  },
  "engagement.exploration": {
    "semantic": "engagement.exploration",
    "label": "Exploration",
    "namespace": "engagement",
    "provider": "Phosphor",
    "providerIcon": "compass",
    "weight": "regular",
    "reserved": true,
    "usage": "Reserved for the named Frontira Exploration engagement.",
    "viewBox": "0 0 256 256",
    "asset": "assets/pictograms/svg/engagement.exploration.svg",
    "body": "<path fill=\"currentColor\" d=\"M128 24a104 104 0 1 0 104 104A104.11 104.11 0 0 0 128 24m0 192a88 88 0 1 1 88-88a88.1 88.1 0 0 1-88 88m44.42-143.16l-64 32a8.05 8.05 0 0 0-3.58 3.58l-32 64A8 8 0 0 0 80 184a8.1 8.1 0 0 0 3.58-.84l64-32a8.05 8.05 0 0 0 3.58-3.58l32-64a8 8 0 0 0-10.74-10.74M138 138l-40.11 20.11L118 118l40.15-20.07Z\"/>"
  },
  "engagement.inspiration": {
    "semantic": "engagement.inspiration",
    "label": "Inspiration",
    "namespace": "engagement",
    "provider": "Phosphor",
    "providerIcon": "broadcast",
    "weight": "regular",
    "reserved": true,
    "usage": "Reserved for the named Frontira Inspiration engagement.",
    "viewBox": "0 0 256 256",
    "asset": "assets/pictograms/svg/engagement.inspiration.svg",
    "body": "<path fill=\"currentColor\" d=\"M128 88a40 40 0 1 0 40 40a40 40 0 0 0-40-40m0 64a24 24 0 1 1 24-24a24 24 0 0 1-24 24m73.71 7.14a80 80 0 0 1-14.08 22.2a8 8 0 0 1-11.92-10.67a63.95 63.95 0 0 0 0-85.33a8 8 0 1 1 11.92-10.67a80.08 80.08 0 0 1 14.08 84.47M69 103.09a64 64 0 0 0 11.26 67.58a8 8 0 0 1-11.92 10.67a79.93 79.93 0 0 1 0-106.67a8 8 0 1 1 11.95 10.67A63.8 63.8 0 0 0 69 103.09M248 128a119.58 119.58 0 0 1-34.29 84a8 8 0 1 1-11.42-11.2a103.9 103.9 0 0 0 0-145.56A8 8 0 1 1 213.71 44A119.58 119.58 0 0 1 248 128M53.71 200.78A8 8 0 1 1 42.29 212a119.87 119.87 0 0 1 0-168a8 8 0 1 1 11.42 11.2a103.9 103.9 0 0 0 0 145.56Z\"/>"
  },
  "engagement.scoping": {
    "semantic": "engagement.scoping",
    "label": "Scoping",
    "namespace": "engagement",
    "provider": "Phosphor",
    "providerIcon": "bounding-box",
    "weight": "regular",
    "reserved": true,
    "usage": "Reserved for the named Frontira Scoping engagement.",
    "viewBox": "0 0 256 256",
    "asset": "assets/pictograms/svg/engagement.scoping.svg",
    "body": "<path fill=\"currentColor\" d=\"M208 96a16 16 0 0 0 16-16V48a16 16 0 0 0-16-16h-32a16 16 0 0 0-16 16v8H96v-8a16 16 0 0 0-16-16H48a16 16 0 0 0-16 16v32a16 16 0 0 0 16 16h8v64h-8a16 16 0 0 0-16 16v32a16 16 0 0 0 16 16h32a16 16 0 0 0 16-16v-8h64v8a16 16 0 0 0 16 16h32a16 16 0 0 0 16-16v-32a16 16 0 0 0-16-16h-8V96Zm-32-48h32v32h-32ZM48 48h32v15.9a.5.5 0 0 0 0 .2V80H48Zm32 160H48v-32h32v15.9a.5.5 0 0 0 0 .2zm128 0h-32v-32h32Zm-24-48h-8a16 16 0 0 0-16 16v8H96v-8a16 16 0 0 0-16-16h-8V96h8a16 16 0 0 0 16-16v-8h64v8a16 16 0 0 0 16 16h8Z\"/>"
  },
  "engagement.sprint": {
    "semantic": "engagement.sprint",
    "label": "Agentic AI Sprint",
    "namespace": "engagement",
    "provider": "Phosphor",
    "providerIcon": "circuitry",
    "weight": "regular",
    "reserved": true,
    "usage": "Reserved for the named Frontira Agentic AI Sprint delivery engagement.",
    "viewBox": "0 0 256 256",
    "asset": "assets/pictograms/svg/engagement.sprint.svg",
    "body": "<path fill=\"currentColor\" d=\"M208 32H48a16 16 0 0 0-16 16v160a16 16 0 0 0 16 16h160a16 16 0 0 0 16-16V48a16 16 0 0 0-16-16M88 160a8 8 0 1 1-8 8a8 8 0 0 1 8-8M48 48h32v97.38a24 24 0 1 0 16 0v-30.07l48 48V208H48Zm160 160h-48v-48a8 8 0 0 0-2.34-5.66L96 92.69V48h32v24a8 8 0 0 0 2.34 5.66l16 16A23.74 23.74 0 0 0 144 104a24 24 0 1 0 24-24a23.74 23.74 0 0 0-10.34 2.35L144 68.69V48h64zM168 96a8 8 0 1 1-8 8a8 8 0 0 1 8-8\"/>"
  },
  "governance.approval": {
    "semantic": "governance.approval",
    "label": "Approval",
    "namespace": "governance",
    "provider": "Phosphor",
    "providerIcon": "seal-check",
    "weight": "regular",
    "reserved": false,
    "usage": "A recorded decision that authorizes work to proceed.",
    "viewBox": "0 0 256 256",
    "asset": "assets/pictograms/svg/governance.approval.svg",
    "body": "<g fill=\"currentColor\"><path d=\"M225.86,102.82c-3.77-3.94-7.67-8-9.14-11.57-1.36-3.27-1.44-8.69-1.52-13.94-.15-9.76-.31-20.82-8-28.51s-18.75-7.85-28.51-8c-5.25-.08-10.67-.16-13.94-1.52-3.56-1.47-7.63-5.37-11.57-9.14C146.28,23.51,138.44,16,128,16s-18.27,7.51-25.18,14.14c-3.94,3.77-8,7.67-11.57,9.14C88,40.64,82.56,40.72,77.31,40.8c-9.76.15-20.82.31-28.51,8S41,67.55,40.8,77.31c-.08,5.25-.16,10.67-1.52,13.94-1.47,3.56-5.37,7.63-9.14,11.57C23.51,109.72,16,117.56,16,128s7.51,18.27,14.14,25.18c3.77,3.94,7.67,8,9.14,11.57,1.36,3.27,1.44,8.69,1.52,13.94.15,9.76.31,20.82,8,28.51s18.75,7.85,28.51,8c5.25.08,10.67.16,13.94,1.52,3.56,1.47,7.63,5.37,11.57,9.14C109.72,232.49,117.56,240,128,240s18.27-7.51,25.18-14.14c3.94-3.77,8-7.67,11.57-9.14,3.27-1.36,8.69-1.44,13.94-1.52,9.76-.15,20.82-.31,28.51-8s7.85-18.75,8-28.51c.08-5.25.16-10.67,1.52-13.94,1.47-3.56,5.37-7.63,9.14-11.57C232.49,146.28,240,138.44,240,128S232.49,109.73,225.86,102.82Zm-11.55,39.29c-4.79,5-9.75,10.17-12.38,16.52-2.52,6.1-2.63,13.07-2.73,19.82-.1,7-.21,14.33-3.32,17.43s-10.39,3.22-17.43,3.32c-6.75.1-13.72.21-19.82,2.73-6.35,2.63-11.52,7.59-16.52,12.38S132,224,128,224s-9.15-4.92-14.11-9.69-10.17-9.75-16.52-12.38c-6.1-2.52-13.07-2.63-19.82-2.73-7-.1-14.33-.21-17.43-3.32s-3.22-10.39-3.32-17.43c-.1-6.75-.21-13.72-2.73-19.82-2.63-6.35-7.59-11.52-12.38-16.52S32,132,32,128s4.92-9.15,9.69-14.11,9.75-10.17,12.38-16.52c2.52-6.1,2.63-13.07,2.73-19.82.1-7,.21-14.33,3.32-17.43S70.51,56.9,77.55,56.8c6.75-.1,13.72-.21,19.82-2.73,6.35-2.63,11.52-7.59,16.52-12.38S124,32,128,32s9.15,4.92,14.11,9.69,10.17,9.75,16.52,12.38c6.1,2.52,13.07,2.63,19.82,2.73,7,.1,14.33.21,17.43,3.32s3.22,10.39,3.32,17.43c.1,6.75.21,13.72,2.73,19.82,2.63,6.35,7.59,11.52,12.38,16.52S224,124,224,128,219.08,137.15,214.31,142.11ZM173.66,98.34a8,8,0,0,1,0,11.32l-56,56a8,8,0,0,1-11.32,0l-24-24a8,8,0,0,1,11.32-11.32L112,148.69l50.34-50.35A8,8,0,0,1,173.66,98.34Z\"/></g>"
  },
  "governance.audit": {
    "semantic": "governance.audit",
    "label": "Audit",
    "namespace": "governance",
    "provider": "Phosphor",
    "providerIcon": "list-checks",
    "weight": "regular",
    "reserved": false,
    "usage": "A traceable inspection of evidence, actions or controls.",
    "viewBox": "0 0 256 256",
    "asset": "assets/pictograms/svg/governance.audit.svg",
    "body": "<g fill=\"currentColor\"><path d=\"M224,128a8,8,0,0,1-8,8H128a8,8,0,0,1,0-16h88A8,8,0,0,1,224,128ZM128,72h88a8,8,0,0,0,0-16H128a8,8,0,0,0,0,16Zm88,112H128a8,8,0,0,0,0,16h88a8,8,0,0,0,0-16ZM82.34,42.34,56,68.69,45.66,58.34A8,8,0,0,0,34.34,69.66l16,16a8,8,0,0,0,11.32,0l32-32A8,8,0,0,0,82.34,42.34Zm0,64L56,132.69,45.66,122.34a8,8,0,0,0-11.32,11.32l16,16a8,8,0,0,0,11.32,0l32-32a8,8,0,0,0-11.32-11.32Zm0,64L56,196.69,45.66,186.34a8,8,0,0,0-11.32,11.32l16,16a8,8,0,0,0,11.32,0l32-32a8,8,0,0,0-11.32-11.32Z\"/></g>"
  },
  "governance.control": {
    "semantic": "governance.control",
    "label": "Governance",
    "namespace": "governance",
    "provider": "Phosphor",
    "providerIcon": "shield-check",
    "weight": "regular",
    "reserved": false,
    "usage": "Authority, permission, control or governed execution.",
    "viewBox": "0 0 256 256",
    "asset": "assets/pictograms/svg/governance.control.svg",
    "body": "<path fill=\"currentColor\" d=\"M208 40H48a16 16 0 0 0-16 16v56c0 52.72 25.52 84.67 46.93 102.19c23.06 18.86 46 25.26 47 25.53a8 8 0 0 0 4.2 0c1-.27 23.91-6.67 47-25.53C198.48 196.67 224 164.72 224 112V56a16 16 0 0 0-16-16m0 72c0 37.07-13.66 67.16-40.6 89.42a129.3 129.3 0 0 1-39.4 22.2a128.3 128.3 0 0 1-38.92-21.81C61.82 179.51 48 149.3 48 112V56h160ZM82.34 141.66a8 8 0 0 1 11.32-11.32L112 148.69l50.34-50.35a8 8 0 0 1 11.32 11.32l-56 56a8 8 0 0 1-11.32 0Z\"/>"
  },
  "governance.escalation": {
    "semantic": "governance.escalation",
    "label": "Escalation",
    "namespace": "governance",
    "provider": "Phosphor",
    "providerIcon": "arrow-up-right",
    "weight": "regular",
    "reserved": false,
    "usage": "An exception or decision elevated to a higher authority.",
    "viewBox": "0 0 256 256",
    "asset": "assets/pictograms/svg/governance.escalation.svg",
    "body": "<g fill=\"currentColor\"><path d=\"M200,64V168a8,8,0,0,1-16,0V83.31L69.66,197.66a8,8,0,0,1-11.32-11.32L172.69,72H88a8,8,0,0,1,0-16H192A8,8,0,0,1,200,64Z\"/></g>"
  },
  "governance.permission": {
    "semantic": "governance.permission",
    "label": "Permission",
    "namespace": "governance",
    "provider": "Phosphor",
    "providerIcon": "lock-key",
    "weight": "regular",
    "reserved": false,
    "usage": "An access grant, restriction or authorization boundary.",
    "viewBox": "0 0 256 256",
    "asset": "assets/pictograms/svg/governance.permission.svg",
    "body": "<g fill=\"currentColor\"><path d=\"M128,112a28,28,0,0,0-8,54.83V184a8,8,0,0,0,16,0V166.83A28,28,0,0,0,128,112Zm0,40a12,12,0,1,1,12-12A12,12,0,0,1,128,152Zm80-72H176V56a48,48,0,0,0-96,0V80H48A16,16,0,0,0,32,96V208a16,16,0,0,0,16,16H208a16,16,0,0,0,16-16V96A16,16,0,0,0,208,80ZM96,56a32,32,0,0,1,64,0V80H96ZM208,208H48V96H208V208Z\"/></g>"
  },
  "governance.proof": {
    "semantic": "governance.proof",
    "label": "Proof",
    "namespace": "governance",
    "provider": "Phosphor",
    "providerIcon": "check-circle",
    "weight": "regular",
    "reserved": false,
    "usage": "Verified outcome, evidence or completed quality gate.",
    "viewBox": "0 0 256 256",
    "asset": "assets/pictograms/svg/governance.proof.svg",
    "body": "<path fill=\"currentColor\" d=\"M173.66 98.34a8 8 0 0 1 0 11.32l-56 56a8 8 0 0 1-11.32 0l-24-24a8 8 0 0 1 11.32-11.32L112 148.69l50.34-50.35a8 8 0 0 1 11.32 0M232 128A104 104 0 1 1 128 24a104.11 104.11 0 0 1 104 104m-16 0a88 88 0 1 0-88 88a88.1 88.1 0 0 0 88-88\"/>"
  },
  "governance.readiness": {
    "semantic": "governance.readiness",
    "label": "Readiness",
    "namespace": "governance",
    "provider": "Phosphor",
    "providerIcon": "gauge",
    "weight": "regular",
    "reserved": false,
    "usage": "A capability, workflow or case assessed as ready to proceed.",
    "viewBox": "0 0 256 256",
    "asset": "assets/pictograms/svg/governance.readiness.svg",
    "body": "<g fill=\"currentColor\"><path d=\"M207.06,72.67A111.24,111.24,0,0,0,128,40h-.4C66.07,40.21,16,91,16,153.13V176a16,16,0,0,0,16,16H224a16,16,0,0,0,16-16V152A111.25,111.25,0,0,0,207.06,72.67ZM224,176H119.71l54.76-75.3a8,8,0,0,0-12.94-9.42L99.92,176H32V153.13c0-3.08.15-6.12.43-9.13H56a8,8,0,0,0,0-16H35.27c10.32-38.86,44-68.24,84.73-71.66V80a8,8,0,0,0,16,0V56.33A96.14,96.14,0,0,1,221,128H200a8,8,0,0,0,0,16h23.67c.21,2.65.33,5.31.33,8Z\"/></g>"
  },
  "intelligence.agent": {
    "semantic": "intelligence.agent",
    "label": "AI agent",
    "namespace": "intelligence",
    "provider": "Phosphor",
    "providerIcon": "robot",
    "weight": "regular",
    "reserved": false,
    "usage": "A bounded software agent, not AI as a decorative concept.",
    "viewBox": "0 0 256 256",
    "asset": "assets/pictograms/svg/intelligence.agent.svg",
    "body": "<path fill=\"currentColor\" d=\"M200 48h-64V16a8 8 0 0 0-16 0v32H56a32 32 0 0 0-32 32v112a32 32 0 0 0 32 32h144a32 32 0 0 0 32-32V80a32 32 0 0 0-32-32m16 144a16 16 0 0 1-16 16H56a16 16 0 0 1-16-16V80a16 16 0 0 1 16-16h144a16 16 0 0 1 16 16Zm-52-56H92a28 28 0 0 0 0 56h72a28 28 0 0 0 0-56m-24 16v24h-24v-24Zm-60 12a12 12 0 0 1 12-12h8v24h-8a12 12 0 0 1-12-12m84 12h-8v-24h8a12 12 0 0 1 0 24m-92-68a12 12 0 1 1 12 12a12 12 0 0 1-12-12m88 0a12 12 0 1 1 12 12a12 12 0 0 1-12-12\"/>"
  },
  "intelligence.reasoning": {
    "semantic": "intelligence.reasoning",
    "label": "Reasoning",
    "namespace": "intelligence",
    "provider": "Phosphor",
    "providerIcon": "brain",
    "weight": "regular",
    "reserved": false,
    "usage": "Interpretation, reasoning or decision support.",
    "viewBox": "0 0 256 256",
    "asset": "assets/pictograms/svg/intelligence.reasoning.svg",
    "body": "<path fill=\"currentColor\" d=\"M248 124a56.11 56.11 0 0 0-32-50.61V72a48 48 0 0 0-88-26.49A48 48 0 0 0 40 72v1.39a56 56 0 0 0 0 101.2V176a48 48 0 0 0 88 26.49A48 48 0 0 0 216 176v-1.41A56.09 56.09 0 0 0 248 124M88 208a32 32 0 0 1-31.81-28.56A56 56 0 0 0 64 180h8a8 8 0 0 0 0-16h-8a40 40 0 0 1-13.33-77.73A8 8 0 0 0 56 78.73V72a32 32 0 0 1 64 0v68.26A47.8 47.8 0 0 0 88 128a8 8 0 0 0 0 16a32 32 0 0 1 0 64m104-44h-8a8 8 0 0 0 0 16h8a56 56 0 0 0 7.81-.56A32 32 0 1 1 168 144a8 8 0 0 0 0-16a47.8 47.8 0 0 0-32 12.26V72a32 32 0 0 1 64 0v6.73a8 8 0 0 0 5.33 7.54A40 40 0 0 1 192 164m16-52a8 8 0 0 1-8 8h-4a36 36 0 0 1-36-36v-4a8 8 0 0 1 16 0v4a20 20 0 0 0 20 20h4a8 8 0 0 1 8 8m-148 8h-4a8 8 0 0 1 0-16h4a20 20 0 0 0 20-20v-4a8 8 0 0 1 16 0v4a36 36 0 0 1-36 36\"/>"
  },
  "intelligence.retrieval": {
    "semantic": "intelligence.retrieval",
    "label": "Retrieval",
    "namespace": "intelligence",
    "provider": "Phosphor",
    "providerIcon": "magnifying-glass",
    "weight": "regular",
    "reserved": false,
    "usage": "Search, retrieval or context lookup.",
    "viewBox": "0 0 256 256",
    "asset": "assets/pictograms/svg/intelligence.retrieval.svg",
    "body": "<path fill=\"currentColor\" d=\"m229.66 218.34l-50.07-50.06a88.11 88.11 0 1 0-11.31 11.31l50.06 50.07a8 8 0 0 0 11.32-11.32M40 112a72 72 0 1 1 72 72a72.08 72.08 0 0 1-72-72\"/>"
  },
  "interface.app": {
    "semantic": "interface.app",
    "label": "Interface",
    "namespace": "interface",
    "provider": "Phosphor",
    "providerIcon": "browser",
    "weight": "regular",
    "reserved": false,
    "usage": "A browser, application or human-facing interface.",
    "viewBox": "0 0 256 256",
    "asset": "assets/pictograms/svg/interface.app.svg",
    "body": "<path fill=\"currentColor\" d=\"M216 40H40a16 16 0 0 0-16 16v144a16 16 0 0 0 16 16h176a16 16 0 0 0 16-16V56a16 16 0 0 0-16-16m0 16v32H40V56Zm0 144H40v-96h176z\"/>"
  },
  "interface.message": {
    "semantic": "interface.message",
    "label": "Message",
    "namespace": "interface",
    "provider": "Phosphor",
    "providerIcon": "chat-circle-text",
    "weight": "regular",
    "reserved": false,
    "usage": "A written message, conversation or communication channel.",
    "viewBox": "0 0 256 256",
    "asset": "assets/pictograms/svg/interface.message.svg",
    "body": "<path fill=\"currentColor\" d=\"M168 112a8 8 0 0 1-8 8H96a8 8 0 0 1 0-16h64a8 8 0 0 1 8 8m-8 24H96a8 8 0 0 0 0 16h64a8 8 0 0 0 0-16m72-8a104 104 0 0 1-152.88 91.82l-34.05 11.35a16 16 0 0 1-20.24-20.24l11.35-34.05A104 104 0 1 1 232 128m-16 0a88 88 0 1 0-164.19 44.06a8 8 0 0 1 .66 6.54L40 216l37.4-12.47a7.9 7.9 0 0 1 2.53-.42a8 8 0 0 1 4 1.08A88 88 0 0 0 216 128\"/>"
  },
  "orchestration.workflow": {
    "semantic": "orchestration.workflow",
    "label": "Workflow",
    "namespace": "orchestration",
    "provider": "Phosphor",
    "providerIcon": "flow-arrow",
    "weight": "regular",
    "reserved": false,
    "usage": "Ordered work, automation or process orchestration.",
    "viewBox": "0 0 256 256",
    "asset": "assets/pictograms/svg/orchestration.workflow.svg",
    "body": "<path fill=\"currentColor\" d=\"m245.66 74.34l-32-32a8 8 0 0 0-11.32 11.32L220.69 72H208c-49.33 0-61.05 28.12-71.38 52.92c-9.38 22.51-16.92 40.59-49.48 42.84a40 40 0 1 0 .1 16c43.26-2.65 54.34-29.15 64.14-52.69C161.41 107 169.33 88 208 88h12.69l-18.35 18.34a8 8 0 0 0 11.32 11.32l32-32a8 8 0 0 0 0-11.32M48 200a24 24 0 1 1 24-24a24 24 0 0 1-24 24\"/>"
  },
  "people.owner": {
    "semantic": "people.owner",
    "label": "Owner",
    "namespace": "people",
    "provider": "Phosphor",
    "providerIcon": "user-circle",
    "weight": "regular",
    "reserved": false,
    "usage": "The individually accountable human owner of work or a decision.",
    "viewBox": "0 0 256 256",
    "asset": "assets/pictograms/svg/people.owner.svg",
    "body": "<g fill=\"currentColor\"><path d=\"M128,24A104,104,0,1,0,232,128,104.11,104.11,0,0,0,128,24ZM74.08,197.5a64,64,0,0,1,107.84,0,87.83,87.83,0,0,1-107.84,0ZM96,120a32,32,0,1,1,32,32A32,32,0,0,1,96,120Zm97.76,66.41a79.66,79.66,0,0,0-36.06-28.75,48,48,0,1,0-59.4,0,79.66,79.66,0,0,0-36.06,28.75,88,88,0,1,1,131.52,0Z\"/></g>"
  },
  "people.team": {
    "semantic": "people.team",
    "label": "Users and team",
    "namespace": "people",
    "provider": "Phosphor",
    "providerIcon": "users-three",
    "weight": "regular",
    "reserved": false,
    "usage": "A team, group of users or accountable human participants.",
    "viewBox": "0 0 256 256",
    "asset": "assets/pictograms/svg/people.team.svg",
    "body": "<path fill=\"currentColor\" d=\"M244.8 150.4a8 8 0 0 1-11.2-1.6A51.6 51.6 0 0 0 192 128a8 8 0 0 1-7.37-4.89a8 8 0 0 1 0-6.22A8 8 0 0 1 192 112a24 24 0 1 0-23.24-30a8 8 0 1 1-15.5-4A40 40 0 1 1 219 117.51a67.94 67.94 0 0 1 27.43 21.68a8 8 0 0 1-1.63 11.21M190.92 212a8 8 0 1 1-13.84 8a57 57 0 0 0-98.16 0a8 8 0 1 1-13.84-8a72.06 72.06 0 0 1 33.74-29.92a48 48 0 1 1 58.36 0A72.06 72.06 0 0 1 190.92 212M128 176a32 32 0 1 0-32-32a32 32 0 0 0 32 32m-56-56a8 8 0 0 0-8-8a24 24 0 1 1 23.24-30a8 8 0 1 0 15.5-4A40 40 0 1 0 37 117.51a67.94 67.94 0 0 0-27.4 21.68a8 8 0 1 0 12.8 9.61A51.6 51.6 0 0 1 64 128a8 8 0 0 0 8-8\"/>"
  },
  "systems.integration": {
    "semantic": "systems.integration",
    "label": "Integration",
    "namespace": "systems",
    "provider": "Phosphor",
    "providerIcon": "plugs-connected",
    "weight": "regular",
    "reserved": false,
    "usage": "Connected software, API integration or system interoperability.",
    "viewBox": "0 0 256 256",
    "asset": "assets/pictograms/svg/systems.integration.svg",
    "body": "<path fill=\"currentColor\" d=\"M237.66 18.34a8 8 0 0 0-11.32 0l-52.4 52.41l-5.37-5.38a32.05 32.05 0 0 0-45.26 0L100 88.69l-6.34-6.35a8 8 0 0 0-11.32 11.32l6.35 6.34l-23.32 23.31a32 32 0 0 0 0 45.26l5.38 5.37l-52.41 52.4a8 8 0 0 0 11.32 11.32l52.4-52.41l5.37 5.38a32 32 0 0 0 45.26 0L156 167.31l6.34 6.35a8 8 0 0 0 11.32-11.32l-6.35-6.34l23.32-23.31a32 32 0 0 0 0-45.26l-5.38-5.37l52.41-52.4a8 8 0 0 0 0-11.32m-116.29 161a16 16 0 0 1-22.62 0l-22.06-22.09a16 16 0 0 1 0-22.62L100 111.31L144.69 156Zm57.94-57.94L156 144.69L111.31 100l23.32-23.31a16 16 0 0 1 22.62 0l22.06 22a16 16 0 0 1 0 22.68ZM88.57 35a8 8 0 0 1 14.86-6l8 20a8 8 0 0 1-14.86 6Zm-64 58A8 8 0 0 1 35 88.57l20 8a8 8 0 0 1-6 14.86l-20-8A8 8 0 0 1 24.57 93m206.86 70a8 8 0 0 1-10.4 4.46l-20-8a8 8 0 1 1 5.97-14.89l20 8a8 8 0 0 1 4.43 10.43m-64 58.06a8 8 0 0 1-14.86 5.94l-8-20a8 8 0 0 1 14.86-6Z\"/>"
  }
};
const pictogramNames = [
  "activity.handoff",
  "activity.meeting",
  "activity.review",
  "activity.workshop",
  "data.database",
  "data.storage",
  "engagement.exploration",
  "engagement.inspiration",
  "engagement.scoping",
  "engagement.sprint",
  "governance.approval",
  "governance.audit",
  "governance.control",
  "governance.escalation",
  "governance.permission",
  "governance.proof",
  "governance.readiness",
  "intelligence.agent",
  "intelligence.reasoning",
  "intelligence.retrieval",
  "interface.app",
  "interface.message",
  "orchestration.workflow",
  "people.owner",
  "people.team",
  "systems.integration"
];

Object.freeze(family);
for (const definition of Object.values(pictograms)) Object.freeze(definition);
Object.freeze(pictograms);
Object.freeze(pictogramNames);

function hasPictogram(name) {
  return typeof name === 'string' && Object.prototype.hasOwnProperty.call(pictograms, name);
}

function getPictogram(name) {
  if (!hasPictogram(name)) {
    throw new RangeError(`Unknown Frontira pictogram: ${String(name)}`);
  }
  return pictograms[name];
}

function getPictogramAsset(name) {
  return getPictogram(name).asset;
}

function escapeAttribute(value) {
  return String(value)
    .replaceAll('&', '&amp;')
    .replaceAll('"', '&quot;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;');
}

function renderPictogram(name, options = {}) {
  if (!options || typeof options !== 'object' || Array.isArray(options)) {
    throw new TypeError('Pictogram options must be an object');
  }
  const definition = getPictogram(name);
  const size = options.size === undefined ? family.defaultSize : options.size;
  if (!Number.isFinite(size) || size < family.minimumSize || size > 512) {
    throw new RangeError(`Pictogram size must be between ${family.minimumSize} and 512`);
  }
  if (options.className !== undefined && typeof options.className !== 'string') {
    throw new TypeError('Pictogram className must be a string');
  }
  if (options.label !== undefined && typeof options.label !== 'string') {
    throw new TypeError('Pictogram label must be a string');
  }

  const className = ['fr-pictogram', options.className?.trim()].filter(Boolean).join(' ');
  const label = options.label?.trim();
  const accessibility = label
    ? `role="img" aria-label="${escapeAttribute(label)}"`
    : 'aria-hidden="true" focusable="false"';

  return `<svg xmlns="http://www.w3.org/2000/svg" class="${escapeAttribute(className)}" width="${size}" height="${size}" style="--fr-pictogram-size: ${size}px" viewBox="${definition.viewBox}" fill="none" data-pictogram="${definition.semantic}" ${accessibility}>${definition.body}</svg>`;
}

module.exports = {
  family,
  pictograms,
  pictogramNames,
  hasPictogram,
  getPictogram,
  getPictogramAsset,
  renderPictogram,
};
