/**
 * Generated by scripts/build-pictograms.mjs. Do not edit directly.
 */

export type PictogramName =
  | 'activity.handoff'
  | 'activity.meeting'
  | 'activity.review'
  | 'activity.workshop'
  | 'data.database'
  | 'data.storage'
  | 'engagement.exploration'
  | 'engagement.inspiration'
  | 'engagement.scoping'
  | 'engagement.sprint'
  | 'governance.approval'
  | 'governance.audit'
  | 'governance.control'
  | 'governance.escalation'
  | 'governance.permission'
  | 'governance.proof'
  | 'governance.readiness'
  | 'intelligence.agent'
  | 'intelligence.reasoning'
  | 'intelligence.retrieval'
  | 'interface.app'
  | 'interface.message'
  | 'orchestration.workflow'
  | 'people.owner'
  | 'people.team'
  | 'systems.integration';

export interface PictogramFamily {
  readonly provider: 'Phosphor';
  readonly package: '@phosphor-icons/core';
  readonly version: '2.1.1';
  readonly weight: 'regular';
  readonly license: 'MIT';
  readonly source: string;
  readonly viewBox: '0 0 256 256';
  readonly defaultSize: number;
  readonly minimumSize: number;
}

export interface PictogramDefinition {
  readonly semantic: PictogramName;
  readonly label: string;
  readonly namespace: string;
  readonly provider: 'Phosphor';
  readonly providerIcon: string;
  readonly weight: 'regular';
  readonly reserved: boolean;
  readonly usage: string;
  readonly viewBox: '0 0 256 256';
  readonly asset: string;
  readonly body: string;
}

export interface RenderPictogramOptions {
  readonly label?: string;
  readonly className?: string;
  readonly size?: number;
}

export const family: Readonly<PictogramFamily>;
export const pictograms: Readonly<Record<PictogramName, Readonly<PictogramDefinition>>>;
export const pictogramNames: readonly PictogramName[];
export function hasPictogram(name: unknown): name is PictogramName;
export function getPictogram(name: PictogramName): Readonly<PictogramDefinition>;
export function getPictogramAsset(name: PictogramName): string;
export function renderPictogram(name: PictogramName, options?: RenderPictogramOptions): string;
